### ISSUE TITLE
Remove loops

### ISSUE THREAD

**Issue by ghost** [Dogcatfee/Archiso_XFCE4#1]
As arch is now x86_64 only you can remove loops from build.sh

#Do all stuff for airootfs
run_once make_basefs
run_once make_packages
run_once make_packages_efi
run_once make_setup_mkinitcpio
run_once make_customize_airootfs
run_once make_boot

#Do all stuff for "iso"
run_once make_boot_extra
run_once make_syslinux
run_once make_isolinux
run_once make_efi
run_once make_efiboot
run_once make_prepare

**Comment by Dogcatfee** [comment]
That's a cool idea, maybe you should try to get that into mainline Archiso. As this repo is just a reconfigured Archiso.
